# Generated by Django 4.0.4 on 2022-05-02 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=255)),
                ('avatar', models.FileField(upload_to='uploads/avatars')),
                ('banner', models.FileField(upload_to='uploads/banners/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=255)),
                ('skills', models.TextField(max_length=255)),
                ('avatar', models.FileField(upload_to='uploads/avatars')),
                ('resume', models.FileField(upload_to='uploads/resumes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=2048)),
                ('tags', models.TextField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.employer')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
