# Generated by Django 4.0.4 on 2022-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='title',
            field=models.CharField(default='Django Developer', max_length=255),
            preserve_default=False,
        ),
    ]
