# Generated by Django 4.0.4 on 2022-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(upload_to='uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='banner',
            field=models.ImageField(upload_to='uploads/banners/'),
        ),
    ]
