# Generated by Django 4.0.4 on 2022-05-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_posting_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='banner',
            field=models.ImageField(default='default.png', upload_to='uploads/banners/'),
        ),
    ]
