# Generated by Django 4.0.4 on 2022-05-04 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_employer_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 14, 46, 47, 422227), verbose_name='date published'),
        ),
    ]
